// Next.js API route support: https://nextjs.org/docs/api-routes/introduction

export default function handler(req, res) {
  res.status(200).json({
    data: [
      {
        id: 1,
        name: "Red Bench",
        category: "people",
        price: 123.89,
        currency: "USD",
        image: {
          src: "https://source.unsplash.com/XKGKZBroImE/600x900/",
          alt: "Red Bench",
        },
        bestseller: true,
        featured: false,
        details: null,
      },
      {
        id: 2,
        name: "Egg Balloon",
        category: "food",
        price: 93.89,
        currency: "USD",
        image: {
          src: "https://source.unsplash.com/Gp-gWG13P-g/600x900/",
          alt: "Red Bench",
        },
        bestseller: false,
        featured: false,
        details: null,
      },
      {
        id: 3,
        name: "Man",
        category: "people",
        price: 760,
        currency: "USD",
        image: {
          src: "https://source.unsplash.com/_sue1D9nFCM/600x900/",
          alt: "",
        },
        bestseller: false,
        featured: false,
        details: null,
      },
      {
        id: 4,
        name: "Architecture",
        category: "landmarks",
        price: 101,
        currency: "USD",
        dimmentions: {
          width: 1020,
          height: 1020,
        },
        image: {
          src: "https://source.unsplash.com/5MTf9XyVVgM/600x900/",
          alt: "",
        },
        bestseller: false,
        featured: false,
        details: null,
      },
      {
        id: 5,
        name: "Christian Dior shop",
        category: "premium",
        price: 101,
        currency: "USD",
        dimmentions: {
          width: 1020,
          height: 1020,
        },
        image: {
          src: "https://source.unsplash.com/_wRcTY0ektE/600x900/",
          alt: "",
        },
        bestseller: false,
        featured: false,
        details: null,
      },
      {
        id: 6,
        name: "Dallas Museum Of Art",
        category: "people",
        price: 101,
        currency: "USD",
        dimmentions: {
          width: 1020,
          height: 1020,
        },
        image: {
          src: "https://source.unsplash.com/QT07ANmTsU8/600x900/",
          alt: "",
        },
        bestseller: false,
        featured: false,
        details: null,
      },
      {
        id: 7,
        name: "Samurai King Restling",
        category: "nature",
        price: 101,
        currency: "USD",
        image: {
          src: "https://source.unsplash.com/3MAmj1ZKSZA/1600x600",
          alt: "",
        },
        bestseller: false,
        featured: true,
        details: {
          dimensions: { width: 1020, height: 1020 },
          size: 15000,
          description:
            "So how did the classical Latin become so incoherent? According to McClintock, a 15th century typesetter likely",
          recommendations: [
            {
              src: "https://source.unsplash.com/aXJdmnxauwY/1600x600",
              alt: "",
            },
            {
              src: "https://source.unsplash.com/aXJdmnxauwY/1600x600",
              alt: "",
            },
            {
              src: "https://source.unsplash.com/aXJdmnxauwY/1600x600",
              alt: "",
            },
          ],
        },
      },
      {
        id: 8,
        name: "Acrylic paintings",
        category: "people",
        price: 353.89,
        currency: "USD",
        image: {
          src: "https://source.unsplash.com/-84767CQrS8/600x900/",
          alt: "Acrylic paintings",
        },
        bestseller: true,
        featured: false,
        details: null,
      },
      {
        id: 9,
        name: "2 Eyes Man",
        category: "food",
        price: 93.89,
        currency: "USD",
        image: {
          src: "https://source.unsplash.com/3NXyodgX254/600x900/",
          alt: "2 Eyes Man",
        },
        bestseller: false,
        featured: false,
        details: null,
      },
      {
        id: 10,
        name: "Hanging chairs",
        category: "people",
        price: 100,
        currency: "USD",
        image: {
          src: "https://source.unsplash.com/NBJ0BBqvdNM/600x900/",
          alt: "Hanging chairs",
        },
        bestseller: false,
        featured: false,
        details: null,
      },
      {
        id: 11,
        name: "Valparaíso’s hills",
        category: "cities",
        price: 101,
        currency: "USD",
        dimmentions: {
          width: 1020,
          height: 1020,
        },
        image: {
          src: "https://source.unsplash.com/WjIB-6UxA5Q/600x900/",
          alt: "Valparaíso’s hills",
        },
        bestseller: false,
        featured: false,
        details: null,
      },
      {
        id: 12,
        name: "Many different paint pots",
        category: "premium",
        price: 46,
        currency: "USD",
        dimmentions: {
          width: 1020,
          height: 1020,
        },
        image: {
          src: "https://source.unsplash.com/krV5aS4jDjA/600x900/",
          alt: "Many different paint pots",
        },
        bestseller: false,
        featured: false,
        details: null,
      },
      {
        id: 13,
        name: "Brushes",
        category: "people",
        price: 422,
        currency: "USD",
        dimmentions: {
          width: 1020,
          height: 1020,
        },
        image: {
          src: "https://source.unsplash.com/MzSqFPLo8CE/600x900/",
          alt: "Brushes",
        },
        bestseller: true,
        featured: false,
        details: null,
      },
      {
        id: 14,
        name: "Black & Yellow",
        category: "people",
        price: 236,
        currency: "USD",
        dimmentions: {
          width: 1020,
          height: 1020,
        },
        image: {
          src: "https://source.unsplash.com/wN9DU73b8_s/600x900/",
          alt: "Black & Yellow",
        },
        bestseller: false,
        featured: false,
        details: null,
      },
      {
        id: 15,
        name: "My Perspective",
        category: "people",
        price: 337.89,
        currency: "USD",
        image: {
          src: "https://source.unsplash.com/ineC_oi7NHs/600x900/",
          alt: "My Perspective",
        },
        bestseller: true,
        featured: false,
        details: null,
      },
      {
        id: 16,
        name: "MONTREAL",
        category: "cities",
        price: 93.89,
        currency: "USD",
        image: {
          src: "https://source.unsplash.com/xb0wLfZH9Zo/600x900/",
          alt: "MONTREAL",
        },
        bestseller: false,
        featured: false,
        details: null,
      },
      {
        id: 17,
        name: "Textures & Patterns",
        category: "people",
        price: 100,
        currency: "USD",
        image: {
          src: "https://source.unsplash.com/woMD-vhzOHI/600x900/",
          alt: "Textures & Patterns",
        },
        bestseller: false,
        featured: false,
        details: null,
      },
      {
        id: 18,
        name: "Flowers in Metal Vase",
        category: "landmarks",
        price: 401,
        currency: "USD",
        dimmentions: {
          width: 1020,
          height: 1020,
        },
        image: {
          src: "https://source.unsplash.com/5TK1F5VfdIk/600x900/",
          alt: "Flowers in Metal Vase",
        },
        bestseller: true,
        featured: false,
        details: null,
      },
      {
        id: 19,
        name: "Palace of Versailles",
        category: "premium",
        price: 101,
        currency: "USD",
        dimmentions: {
          width: 1020,
          height: 1020,
        },
        image: {
          src: "https://source.unsplash.com/1rBg5YSi00c/600x900/",
          alt: "Palace of Versailles",
        },
        bestseller: false,
        featured: false,
        details: null,
      },
      {
        id: 20,
        name: "Blind Statue",
        category: "people",
        price: 101,
        currency: "USD",
        dimmentions: {
          width: 1020,
          height: 1020,
        },
        image: {
          src: "https://source.unsplash.com/tKgcMR8saYA/600x900/",
          alt: "Blind Statue",
        },
        bestseller: false,
        featured: false,
        details: null,
      },
      {
        id: 21,
        name: "Christian King",
        category: "people",
        price: 101,
        currency: "USD",
        dimmentions: {
          width: 1020,
          height: 1020,
        },
        image: {
          src: "https://source.unsplash.com/D5nh6mCW52c/600x900/",
          alt: "Christian King",
        },
        bestseller: false,
        featured: false,
        details: null,
      },
    ],
  });
}
